apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kust-stage
  namespace: flux-system
spec:
  interval: 10s
  path: ./stage 		### all apps in this path will be created and reconcilied
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
