apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-dev
  name: nginx-dev
  namespace: nginx-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-dev
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-dev
    spec:
      containers:
      - image: nginx
        name: nginx-dev
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
