apiVersion: v1
kind: Service
metadata:
  namespace: nginx-dev
  creationTimestamp: null
  labels:
    app: nginx-dev
  name: nginx-dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-dev
  type: NodePort
status:
  loadBalancer: {}
