apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kust-dev
  namespace: flux-system
spec:
  dependsOn:
  - name: kust-common
  interval: 1m40s
  path: ./dev 		### all apps in this path will be created and reconcilied
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
