apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kust-common
  namespace: flux-system
spec:
  interval: 10s
  path: ./common
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
