apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prod-kust-private-repo
  namespace: flux-system
spec:
  interval: 10s
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: source-private-repo
  targetNamespace: solar-system-prod
