apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: source-solar-system
  namespace: flux-system
spec:
  interval: 10s
  ref:
    branch: main
  url: https://github.com/sidd-harth/gitops-argocd
